spring.application.name=kathmandu-aqi

# Server
server.port=8080

# PostgreSQL - Railway variables
spring.datasource.url=jdbc:postgresql://${PGHOST}:${PGPORT}/${PGDATABASE}
spring.datasource.username=${PGUSER}
spring.datasource.password=${PGPASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false

# OpenAQ API
openaq.api.key=1d8b65a033603bcae16756717be97487ae84f65e17d3280f6cbca299aa4ec93b
openaq.api.base-url=https://api.openaq.org/v3
openaq.kathmandu.coordinates=27.7172,85.3240
openaq.kathmandu.radius=25000

# CORS
cors.allowed-origins=http://localhost:3000,http://127.0.0.1:5500,https://kathmandu-aqi-production.up.railway.app
